apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-test
  name: docker-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-test
  strategy: {}
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
        - image: 862839345820.dkr.ecr.ap-south-1.amazonaws.com/docker-deploy-1:latest
          name: docker-image-aws
          resources:
            limits:
              cpu: 0.5
              memory: 300M
            requests:
              cpu: 0.5
              memory: 300M
          ports:
            - containerPort: 3000